### ISSUE TITLE
Way to add words to dictionairy

### ISSUE THREAD

**Issue by kevindotzhang** [ng-web-apis/speech#2]
# 🚀 Feature request

### Is your feature request related to a problem?

I'm trying to make a demo and want to add certain words to the dictionairy.

### Describe the solution you'd like

Find a way to add words to the Web Speech API dictionary.

### Describe alternatives you've considered

I was looking at app.component.ts and was thinking that it's possible to add words as "keywords" such as the show/hide sidebar portion and instead of inputting a command it puts the word. This didn't make sense after thinking about it since in order to activate the command you'd have to say the word so another thought was to say the word you wanted to add and it will come up with a word that it thinks you were trying to say and that would be the keyword which can then make it enter a different word, however, this would limit/restrict the use of the original word. The final solution would be adding a way to spell out words, if you tried now, the letters will appear individually with spaces in between them.

**Comment by waterplea** [comment]
This library is just a proxy to the native Web Speech API. As far as I know, there's no way to change its vocabulary. Grammar objects, although defined in specs, are not implemented by any browser. Feel free to reopen if my information is wrong :)
